### ISSUE TITLE
th-lift's instance for Lift (Ratio a) is too narrow

### ISSUE THREAD

**Issue by RyanGlScott** [mboes/th-lift#14]
`template-haskell-2.10.0.0` introduces [an instance for `Lift (Ratio a)`](https://phabricator.haskell.org/diffusion/GHC/browse/master/libraries/template-haskell/Language/Haskell/TH/Syntax.hs;d4b645337d2d1a2fb4cfbbef0e5a160c5384f792$493-494):

```haskell
instance Integral a => Lift (Ratio a) where
    lift x = return (LitE (RationalL (toRational x)))
```

However, `th-lift` currently defines [an instance only for `Lift Rational`](https://github.com/mboes/th-lift/blob/3fa3a11e92c961760910d476e2856cfbbd2a31cb/src/Language/Haskell/TH/Lift.hs#L159-160), which means `th-lift` users with older versions of `template-haskell` cannot take advantage of the more general instance. Can you change the implementation in `th-lift` to match `template-haskell-2.10.0.0`?

**Comment by mboes** [comment]
New release uploaded to Hackage. Thanks!
