### ISSUE TITLE
Add capabilities of DeriveLift

### ISSUE THREAD

**Issue by RyanGlScott** [mboes/th-lift#17]
GHC 8.0 will introduce the `DeriveLift` extension which, at the moment, can do things that `th-lift` cannot. This issue serves to track these discrepancies:
- [X] `DeriveLift` can handle empty datatypes (e.g., `data Empty deriving Lift`) and datatypes with certain unboxed arguments (e.g., `data UnboxedInt = UnboxedInt Int# deriving Lift`). ([Merged](https://github.com/mboes/th-lift/pull/18))
- [X] `DeriveLift` can handle datatypes with complex instance contexts (e.g., `newtype Fix = In (f (Fix f)); instance Lift (f (Fix f)) => Lift (Fix f) where ...`). ([Merged](https://github.com/mboes/th-lift/pull/19))
- [ ] `DeriveLift` can handle data family instances.

I'll try to tackle these one at a time.

**Comment by RyanGlScott** [comment]
On the topic of data families, there's quite a bit of tricky conditional logic needed to get Template Haskell to play nicely with data family instances on old versions of GHC (see, for instance, [Trac #9692](https://ghc.haskell.org/trac/ghc/ticket/9692), which you'd have to work around on GHC 7.6 and 7.8).

Thankfully, there's the [`th-abstraction`](http://hackage.haskell.org/package/th-abstraction) library, a dependency-less library that grants you the ability to reify data family instances in a way that works around these old bugs. `th-abstraction` supports all the way back to GHC 7.0, so would you be willing to add it as a dependency in pursuit of resolving this issue?

**Comment by mboes** [comment]
Sure!
