### ISSUE TITLE
support user-specified instance contexts

### ISSUE THREAD

**Issue by nfrisby** [mboes/th-lift#21]
Note that this issue would provide a workaround for #20.

The interface to `th-lift` would be more expressive if it exported a `deriveLiftExp` such that users could write something like the following:

    instance (MyCustomContext a b c) => Lift (T a b c) where
      lift = $(deriveLiftExp ''T)

I anticipate that the logic necessary for `deriveLiftExp` is already in-place, merely not exposed as part of the interface.

**Comment by RyanGlScott** [comment]
Good news: by sheer coincidence, I [happened to implement](https://github.com/mboes/th-lift/pull/19) this very feature a couple of days ago.

**Comment by nfrisby** [comment]
Ha! Fantastic! Thanks.

**Comment by mboes** [comment]
Closing as dup of #17. I was waiting for @RyanGlScott to finish implementing all of that ticket before putting out a new release but I can do that early given the interest.
