### ISSUE TITLE
deriveLift' calls reifyRoles

### ISSUE THREAD

**Issue by ddssff** [mboes/th-lift#25]
Attempting to use deriveLift' to generate Lift instances for an as yet undeclared type, it fails because it calls reifyRoles on the type name.  I checked and the result of reifyRoles on my type once declared is the empty list.  Maybe an option to supply this value would be helpful?

**Comment by ddssff** [comment]
My diagnosis of the issue I'm seeing may be premature.

**Comment by mboes** [comment]
Fixed by #26.
