### ISSUE TITLE
Changelog was last updated in 2015

### ISSUE THREAD

**Issue by 23Skidoo** [mboes/th-lift#34]
http://hackage.haskell.org/package/th-lift-0.7.11/changelog

Would be nice not to have to go to GitHub to find out what's new in 0.7.10. Also it should include version numbers instead of just dates.

**Comment by mboes** [comment]
Removed the stale changelog for now. This package is in maintenance mode so feature set has been very stable for years. New releases just adapt to upstream changes in Template Haskell.

**Comment by mboes** [comment]
In the end, I kept the changelog and rewrote it in Markdown format. It was previously in the standard GNU format for changelogs.

**Comment by 23Skidoo** [comment]
Great, thanks!
