### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by erikd** [mboes/th-lift#37]
Commit 8969cfb5f670d09d7d18b1e55325ada82c300ddd bumped the upper bound of the temple-haskell dependency to allow it to compile with ghc 8.6.

Would really love a release of this so I can make sure my stuff works with ghc 8.6.

Thanks!

**Comment by mboes** [comment]
Sure thing. Done as v0.7.11.

**Comment by erikd** [comment]
Thanks!
